// Path: MauiApp/Models/Payroll.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HrmApp.Models;

/// <summary>
/// Monthly payroll record with full Turkish legal breakdown.
/// Generated by PayrollService using Salary definitions.
/// </summary>
public class Payroll
{
    [Key]
    public int Id { get; set; }

    [Required]
    public int EmployeeId { get; set; }

    [ForeignKey(nameof(EmployeeId))]
    public Employee? Employee { get; set; }

    [Required, MaxLength(7)]
    public string Period { get; set; } = string.Empty; // YYYY-MM

    // ══════════════════════════════════════════════════════════════
    //  BRÜT KAZANÇLAR (Gross Earnings)
    // ══════════════════════════════════════════════════════════════

    /// <summary>Brüt maaş</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal GrossSalary { get; set; }

    /// <summary>Yemek yardımı</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal MealAllowance { get; set; }

    /// <summary>Yol / ulaşım yardımı</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal TransportAllowance { get; set; }

    /// <summary>Özel sağlık sigortası</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal PrivateHealthInsurance { get; set; }

    /// <summary>Aile yardımı</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal FamilyAllowance { get; set; }

    /// <summary>Konut yardımı</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal HousingAllowance { get; set; }

    /// <summary>Eğitim yardımı</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal EducationAllowance { get; set; }

    /// <summary>Prim / bonus</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal BonusAmount { get; set; }

    /// <summary>Fazla mesai ücreti (brüt/225 × 1.5 × saat)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal OvertimePay { get; set; }

    /// <summary>Toplam fazla mesai saati (puantajdan)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal OvertimeHours { get; set; }

    /// <summary>Yemek yardımı çalışılan gün sayısı (haftasonları hariç)</summary>
    public int MealWorkDays { get; set; }

    /// <summary>Toplam brüt kazanç</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalGross { get; set; }

    // ══════════════════════════════════════════════════════════════
    //  YASAL KESİNTİLER (Legal Deductions — Worker)
    // ══════════════════════════════════════════════════════════════

    /// <summary>SGK işçi payı (%14)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal SgkWorker { get; set; }

    /// <summary>İşsizlik sigortası işçi payı (%1)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal UnemploymentWorker { get; set; }

    /// <summary>Gelir vergisi (kümülatif dilimli)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal IncomeTax { get; set; }

    /// <summary>Damga vergisi (%0.759)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal StampTax { get; set; }

    /// <summary>Toplam kesinti</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalDeductions { get; set; }

    // ══════════════════════════════════════════════════════════════
    //  NET MAAŞ
    // ══════════════════════════════════════════════════════════════

    /// <summary>Net ele geçen = TotalGross - TotalDeductions</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal NetSalary { get; set; }

    // ══════════════════════════════════════════════════════════════
    //  İŞVEREN MALİYETİ (Employer Cost — informational)
    // ══════════════════════════════════════════════════════════════

    /// <summary>SGK işveren payı (%20.5)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal SgkEmployer { get; set; }

    /// <summary>İşsizlik sigortası işveren payı (%2)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal UnemploymentEmployer { get; set; }

    /// <summary>Toplam işveren maliyeti (brüt + işveren payları)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalEmployerCost { get; set; }

    // ── Meta ─────────────────────────────────────────────────────

    /// <summary>Kümülatif vergi matrahı (yılbaşından bu aya kadar)</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal CumulativeTaxBase { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // ── Backward compatibility ───────────────────────────────────
    // These map old field names to new ones so existing UI doesn't break

    [NotMapped] public decimal BaseSalary => GrossSalary;
    [NotMapped] public decimal Allowances => TotalGross - GrossSalary;
    [NotMapped] public decimal Deductions => TotalDeductions;
    [NotMapped] public decimal FinalSalary => NetSalary;
}